name: deploy.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  VERSION: 3.0.0

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Actividad 1: Descargar el código fuente.
    - name: Descargar el código fuente
      uses: actions/checkout@v4

    # Configurar entorno de ejecución
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # Actividad 2: Instalar dependencias.
    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    # Actividad 3: Ejecutar pruebas automatizadas.
    - name: Ejecutar pruebas automatizadas
      run: |
        pytest test_app.py

    # Actividad 4: Ejecutar la aplicación.
    # Usamos '&' para correrla en segundo plano 3 segundos, verificarla y cerrarla sin colgar el flujo.
    - name: Ejecutar la aplicación
      run: |
        python app.py &
        sleep 3
        curl http://127.0.0.1:5000 || exit 1

    # Actividad 5: Simular una fase de despliegue.
    - name: Simular una fase de despliegue
      run: |
        echo "Ejecutando simulacion de despliegue en entorno de pruebas..."

    # Actividad 6: Construir una imagen Docker.
    # Nomenclatura requerida: ghcr.io/<usuario>/ejercicio:3.0.0
    - name: Construir una imagen Docker
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/ejercicio:${{ env.VERSION }} .

    # Actividad 7: Autenticarse en GitHub Container Registry.
    - name: Autenticarse en GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Actividad 8: Publicar la imagen generada.
    - name: Publicar la imagen generada
      run: |
        docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/ejercicio:${{ env.VERSION }}